version: "3.9"
services:
  nextjs14-todo:
    image: postgres
    restart: always
    container_name: nextjs14-todo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
volumes:
  postgres:
